package com.shanqijie.fitnessapp.domain

import java.util.Locale
import java.util.concurrent.ConcurrentHashMap

object ExerciseChineseNameTranslator {
    private val cjkRegex = Regex("[\\u4e00-\\u9fff]")
    private val latinRegex = Regex("[A-Za-z]+")
    private val spaceRegex = Regex("\\s+")
    private val tokenSplitRegex = Regex("\\s+")
    private val punctuationRegex = Regex("[()\\[\\],:]")
    private val separatorRegex = Regex("[-_]")
    private val numberRegex = Regex("\\d+")
    private val translationCache = ConcurrentHashMap<String, String>()

    private val exactNameMap = mapOf(
        "smith bench press" to "史密斯机卧推",
        "dumbbell bench press" to "哑铃卧推",
        "dumbbell incline bench press" to "上斜哑铃卧推",
        "lever seated fly" to "器械夹胸",
        "smith squat" to "史密斯机深蹲",
        "smith full squat" to "史密斯机全蹲",
        "smith chair squat" to "史密斯机箱式深蹲",
        "smith hack squat" to "史密斯机哈克深蹲",
        "cable lat pulldown full range of motion" to "绳索高位下拉全程",
        "barbell bent over row" to "杠铃俯身划船",
        "sled 45° leg press" to "45度腿举",
        "3/4 sit-up" to "四分之三仰卧起坐",
        "45° side bend" to "45度侧屈",
        "machine" to "器械",
        "free-weight" to "自由重量",
        "free weight" to "自由重量",
        "cardio" to "有氧",
        "bodyweight" to "自重",
        "body-weight" to "自重",
        "custom" to "自定义",
    )

    private val phraseMap = listOf(
        "full range of motion" to "全程",
        "smith machine" to "史密斯机",
        "body weight" to "自重",
        "stability ball" to "稳定球",
        "medicine ball" to "药球",
        "resistance band" to "弹力带",
        "leverage machine" to "固定器械",
        "sled machine" to "雪橇器械",
        "elliptical machine" to "椭圆机",
        "skierg machine" to "滑雪测功仪",
        "stepmill machine" to "登阶机",
        "stationary bike" to "固定单车",
        "upper body ergometer" to "上肢测功仪",
        "wheel roller" to "健腹轮",
        "trap bar" to "六角杠",
        "upper arms" to "上臂",
        "lower arms" to "前臂",
        "upper legs" to "大腿",
        "lower legs" to "小腿",
        "upper back" to "上背",
        "cardiovascular system" to "心肺系统",
        "serratus anterior" to "前锯肌",
        "levator scapulae" to "肩胛提肌",
        "ez barbell" to "曲杆杠铃",
        "ez bar" to "曲杆",
        "v bar" to "窄握柄",
        "t bar" to "丁字杠",
        "bench press" to "卧推",
        "chest press" to "胸推",
        "shoulder press" to "肩推",
        "military press" to "推举",
        "leg press" to "腿举",
        "behind neck press" to "颈后推举",
        "behind head military press" to "头后推举",
        "reverse grip press" to "反握推举",
        "close grip bench press" to "窄握卧推",
        "wide grip bench press" to "宽握卧推",
        "decline bench press" to "下斜卧推",
        "incline bench press" to "上斜卧推",
        "bent over row" to "俯身划船",
        "one arm row" to "单臂划船",
        "rear delt row" to "后束划船",
        "upright row" to "直立划船",
        "narrow row" to "窄握划船",
        "wide grip row" to "宽握划船",
        "lat pulldown" to "高位下拉",
        "lateral pulldown" to "侧向下拉",
        "straight arm pulldown" to "直臂下拉",
        "triceps pushdown" to "肱三头下压",
        "tricep pushdown" to "肱三头下压",
        "triceps extension" to "肱三头臂屈伸",
        "tricep extension" to "肱三头臂屈伸",
        "bicep curl" to "肱二头弯举",
        "biceps curl" to "肱二头弯举",
        "preacher curl" to "牧师凳弯举",
        "hammer curl" to "锤式弯举",
        "concentration curl" to "集中弯举",
        "wrist curl" to "腕弯举",
        "reverse wrist curl" to "反向腕弯举",
        "calf raise" to "提踵",
        "calf raises" to "提踵",
        "toe raise" to "提踵",
        "lateral raise" to "侧平举",
        "lateral raises" to "侧平举",
        "front raise" to "前平举",
        "shoulder raises" to "肩部提举",
        "leg raise" to "举腿",
        "knee raise" to "提膝",
        "hanging knee raise" to "悬垂提膝",
        "sit up" to "仰卧起坐",
        "sit-up" to "仰卧起坐",
        "push up" to "俯卧撑",
        "push-up" to "俯卧撑",
        "pull up" to "引体向上",
        "pull-up" to "引体向上",
        "chin up" to "反握引体",
        "chin-up" to "反握引体",
        "good morning" to "早安式",
        "deadlift" to "硬拉",
        "romanian deadlift" to "罗马尼亚硬拉",
        "stiff leg deadlift" to "直腿硬拉",
        "split squat" to "分腿蹲",
        "hack squat" to "哈克深蹲",
        "sumo squat" to "相扑深蹲",
        "goblet squat" to "高脚杯深蹲",
        "front squat" to "前蹲",
        "low bar squat" to "低杠深蹲",
        "back squat" to "后蹲",
        "hip thrust" to "臀推",
        "hip thrusts" to "臀推",
        "hip raise" to "抬髋",
        "glute bridge" to "臀桥",
        "russian twist" to "俄罗斯转体",
        "mountain climber" to "登山跑",
        "jump squat" to "跳深蹲",
        "box jump" to "跳箱",
        "burpee" to "波比跳",
        "jumping jack" to "开合跳",
        "skull crusher" to "仰卧臂屈伸",
        "skullcrusher" to "仰卧臂屈伸",
        "face pull" to "面拉",
        "pallof press" to "帕洛夫推",
        "turkish get up" to "土耳其起身",
        "farmer carry" to "农夫行走",
        "battle rope" to "战绳",
        "battling rope" to "战绳",
        "cable fly" to "绳索飞鸟",
        "dumbbell fly" to "哑铃飞鸟",
        "barbell curl" to "杠铃弯举",
        "dumbbell curl" to "哑铃弯举",
        "cable curl" to "绳索弯举",
        "reverse curl" to "反向弯举",
        "zottman curl" to "佐特曼弯举",
        "arnold press" to "阿诺德推举",
        "sissy squat" to "西西深蹲",
        "pistol squat" to "手枪深蹲",
        "cossack squat" to "哥萨克深蹲",
        "cobra pose" to "眼镜蛇式",
        "child pose" to "婴儿式",
    )

    private val phraseRules by lazy(LazyThreadSafetyMode.PUBLICATION) {
        phraseMap
            .sortedByDescending { it.first.length }
            .map { (english, chinese) ->
                Regex("(?<![a-z])${Regex.escape(english)}(?![a-z])") to chinese
            }
    }

    private val wordMap = mapOf(
        "ab" to "腹",
        "abs" to "腹肌",
        "abdominal" to "腹部",
        "abduction" to "外展",
        "abductor" to "外展肌",
        "abductors" to "外展肌",
        "adduction" to "内收",
        "adductor" to "内收肌",
        "adductors" to "内收肌",
        "advanced" to "进阶",
        "air" to "空中",
        "all" to "全",
        "alternate" to "交替",
        "alternating" to "交替",
        "angle" to "角度",
        "angled" to "斜角",
        "ankle" to "踝",
        "ankles" to "踝",
        "anti" to "抗",
        "apart" to "分开",
        "archer" to "弓箭手",
        "arm" to "手臂",
        "arms" to "手臂",
        "arnold" to "阿诺德",
        "around" to "环绕",
        "assisted" to "辅助",
        "astride" to "跨坐",
        "attachment" to "附件",
        "back" to "背部",
        "backward" to "后向",
        "balance" to "平衡",
        "ball" to "球",
        "band" to "弹力带",
        "bar" to "杆",
        "barbell" to "杠铃",
        "bars" to "双杠",
        "basic" to "基础",
        "bear" to "熊爬",
        "behind" to "后",
        "bench" to "卧推凳",
        "benches" to "训练凳",
        "bend" to "屈",
        "bends" to "屈",
        "bent" to "俯身",
        "bicep" to "肱二头",
        "biceps" to "肱二头",
        "bicycle" to "自行车",
        "big" to "大幅",
        "bike" to "单车",
        "blaster" to "训练器",
        "board" to "板",
        "body" to "身体",
        "bodyweight" to "自重",
        "bosu" to "波速球",
        "both" to "双侧",
        "bottoms" to "壶底向上",
        "bowling" to "保龄球式",
        "box" to "箱",
        "boxing" to "拳击",
        "bradford" to "布拉德福德",
        "breeding" to "支撑",
        "bridge" to "桥",
        "bug" to "死虫",
        "butt" to "臀部",
        "butterfly" to "蝴蝶式",
        "cable" to "绳索",
        "cage" to "框架",
        "calf" to "小腿",
        "calves" to "小腿",
        "cambered" to "弯杆",
        "cardio" to "有氧",
        "cardiovascular" to "心肺",
        "captains" to "船长椅",
        "carry" to "行走",
        "caster" to "滑轮",
        "cat" to "猫式",
        "catch" to "接",
        "chair" to "椅式",
        "chest" to "胸部",
        "chin" to "反握引体",
        "circles" to "绕环",
        "circular" to "环形",
        "clap" to "击掌",
        "clasped" to "握手",
        "clean" to "翻站",
        "climb" to "攀爬",
        "climber" to "登山",
        "clock" to "钟摆",
        "close" to "窄握",
        "closer" to "内收",
        "cobra" to "眼镜蛇",
        "cocoons" to "卷腹抱膝",
        "concentration" to "集中",
        "contralateral" to "对侧",
        "crab" to "蟹步",
        "crawl" to "爬行",
        "cross" to "交叉",
        "crossover" to "交叉",
        "crossovers" to "交叉",
        "crunch" to "卷腹",
        "crunches" to "卷腹",
        "crusher" to "臂屈伸",
        "cuban" to "古巴式",
        "curl" to "弯举",
        "curls" to "弯举",
        "curtsey" to "交叉弓步",
        "cycle" to "循环",
        "dead" to "硬拉",
        "decline" to "下斜",
        "deep" to "深",
        "degrees" to "度",
        "delt" to "三角肌",
        "delts" to "三角肌",
        "deltoid" to "三角肌",
        "depth" to "深度",
        "diagonal" to "对角",
        "diamond" to "钻石",
        "dip" to "臂屈伸",
        "dips" to "臂屈伸",
        "dog" to "犬式",
        "donkey" to "驴式",
        "double" to "双",
        "down" to "下",
        "drag" to "拖拉",
        "drive" to "驱动",
        "drop" to "下放",
        "dumbbell" to "哑铃",
        "dumbbells" to "哑铃",
        "dynamic" to "动态",
        "elbow" to "肘",
        "elevated" to "抬高",
        "elevator" to "升降",
        "elliptical" to "椭圆机",
        "ergometer" to "测功仪",
        "exercise" to "训练",
        "extended" to "伸展",
        "extension" to "伸展",
        "external" to "外旋",
        "ez" to "曲杆",
        "face" to "面部",
        "facing" to "面向",
        "fallout" to "前伸",
        "farmers" to "农夫",
        "feet" to "脚",
        "female" to "女性",
        "figure" to "四字",
        "finger" to "手指",
        "fixed" to "固定",
        "forearms" to "前臂",
        "flag" to "旗式",
        "flat" to "平板",
        "flexion" to "屈曲",
        "flexor" to "屈肌",
        "flip" to "翻转",
        "floor" to "地面",
        "flutter" to "打水",
        "fly" to "飞鸟",
        "flyes" to "飞鸟",
        "forward" to "前",
        "fours" to "四点",
        "frankenstein" to "弗兰肯斯坦",
        "free" to "自由",
        "french" to "法式",
        "frog" to "青蛙",
        "front" to "前",
        "full" to "全程",
        "gironda" to "吉隆达",
        "glute" to "臀",
        "glutes" to "臀",
        "gluteus" to "臀大肌",
        "goblet" to "高脚杯",
        "good" to "早安式",
        "gorilla" to "猩猩式",
        "gravity" to "重力",
        "grip" to "握",
        "gripless" to "无握",
        "gripper" to "握力器",
        "groin" to "腹股沟",
        "ground" to "地面",
        "guillotine" to "断头台式",
        "hack" to "哈克",
        "half" to "半程",
        "ham" to "腘绳肌",
        "hammer" to "锤式",
        "hamstring" to "腘绳肌",
        "hamstrings" to "腘绳肌",
        "hand" to "手",
        "handle" to "把手",
        "hands" to "双手",
        "handstand" to "倒立",
        "hang" to "悬挂",
        "hanging" to "悬垂",
        "head" to "头",
        "heel" to "脚跟",
        "high" to "高位",
        "hindu" to "印度式",
        "hip" to "髋",
        "hook" to "钩握",
        "hops" to "小跳",
        "horizontal" to "水平",
        "hug" to "抱",
        "hyper" to "过伸",
        "hyperextension" to "背伸",
        "impossible" to "高难",
        "inchworm" to "尺蠖",
        "incline" to "上斜",
        "inner" to "内侧",
        "inside" to "内侧",
        "intermediate" to "中阶",
        "internal" to "内旋",
        "inverse" to "反向",
        "inverted" to "倒置",
        "iron" to "铁十字",
        "isometric" to "等长",
        "jack" to "开合跳",
        "jackknife" to "折刀",
        "janda" to "扬达",
        "jefferson" to "杰斐逊",
        "jerk" to "挺举",
        "jm" to "杰姆式",
        "judo" to "柔道式",
        "jump" to "跳",
        "jumps" to "跳",
        "kayak" to "皮划艇",
        "kettlebell" to "壶铃",
        "kick" to "踢",
        "kickback" to "后踢",
        "kickbacks" to "后踢",
        "kicks" to "踢腿",
        "kipping" to "摆动借力",
        "knee" to "膝",
        "kneeling" to "跪姿",
        "knees" to "膝",
        "knife" to "折刀",
        "korean" to "韩式",
        "l" to "直角",
        "landmine" to "地雷架",
        "lat" to "背阔",
        "lats" to "背阔肌",
        "lateral" to "侧向",
        "lean" to "前倾",
        "left" to "左",
        "leg" to "腿",
        "legged" to "单腿",
        "legs" to "腿",
        "lever" to "器械",
        "lift" to "提拉",
        "lifting" to "举",
        "low" to "低位",
        "lower" to "下",
        "lunge" to "弓步",
        "lying" to "仰卧",
        "machine" to "器械",
        "major" to "主肌",
        "male" to "男性",
        "maltese" to "马耳他式",
        "march" to "踏步",
        "medicine" to "药球",
        "middle" to "中",
        "military" to "推举",
        "mixed" to "混合",
        "modified" to "改良",
        "monster" to "怪兽",
        "morning" to "早安式",
        "motion" to "动作",
        "mountain" to "登山",
        "multiple" to "多次",
        "muscle" to "双力臂",
        "narrow" to "窄",
        "neck" to "颈",
        "negative" to "离心",
        "neutral" to "中立握",
        "oblique" to "腹斜肌",
        "off" to "离地",
        "olympic" to "奥林匹克",
        "one" to "单",
        "outer" to "外侧",
        "outside" to "外侧",
        "outstretched" to "伸直",
        "over" to "过顶",
        "overhand" to "正握",
        "overhead" to "过顶",
        "pad" to "垫",
        "palm" to "掌心",
        "palms" to "掌心",
        "parallel" to "平行",
        "pass" to "传递",
        "pec" to "胸肌",
        "pectoralis" to "胸大肌",
        "pectorals" to "胸肌",
        "pelvic" to "骨盆",
        "pendlay" to "潘德雷",
        "peroneals" to "腓骨肌",
        "pike" to "折体",
        "piriformis" to "梨状肌",
        "planche" to "俄挺",
        "plank" to "平板支撑",
        "platform" to "平台",
        "plus" to "加强",
        "plyo" to "增强式",
        "point" to "点地",
        "pose" to "姿势",
        "position" to "姿势",
        "posterior" to "后侧",
        "potty" to "蹲姿",
        "pov" to "视角",
        "power" to "力量",
        "preacher" to "牧师凳",
        "press" to "推",
        "presses" to "推",
        "prisoner" to "囚徒",
        "pronated" to "旋前",
        "pronation" to "旋前",
        "prone" to "俯卧",
        "pull" to "拉",
        "pulldown" to "下拉",
        "pulley" to "滑轮",
        "pullover" to "上拉",
        "push" to "推",
        "pushdown" to "下压",
        "pyramid" to "金字塔",
        "quad" to "股四头肌",
        "quads" to "股四头肌",
        "quarter" to "四分之一",
        "quick" to "快速",
        "rack" to "架上",
        "raise" to "提举",
        "raised" to "抬高",
        "raises" to "提举",
        "range" to "幅度",
        "reach" to "伸手",
        "rear" to "后束",
        "reclining" to "后仰",
        "rectus" to "腹直肌",
        "release" to "释放",
        "renegade" to "俯撑划船",
        "reps" to "次数",
        "resistance" to "阻力",
        "response" to "反应",
        "retractor" to "回缩",
        "revers" to "反向",
        "reverse" to "反向",
        "reversed" to "反向",
        "ring" to "吊环",
        "rocking" to "摇摆",
        "rocky" to "洛奇式",
        "roller" to "健腹轮",
        "rollerer" to "滚轮",
        "rollerout" to "健腹轮推出",
        "romanian" to "罗马尼亚",
        "rope" to "绳",
        "ropes" to "绳",
        "rotary" to "旋转",
        "rotate" to "旋转",
        "rotation" to "旋转",
        "rotational" to "旋转",
        "round" to "圆形",
        "row" to "划船",
        "run" to "跑",
        "runners" to "跑者",
        "russian" to "俄罗斯",
        "saw" to "锯式",
        "scapula" to "肩胛",
        "scapular" to "肩胛",
        "scissor" to "剪刀",
        "scott" to "斯科特",
        "seated" to "坐姿",
        "seesaw" to "跷跷板",
        "self" to "自助",
        "semi" to "半",
        "sequence" to "序列",
        "short" to "短程",
        "shoulder" to "肩",
        "shoulders" to "肩",
        "shrug" to "耸肩",
        "side" to "侧",
        "single" to "单",
        "sit" to "坐",
        "sitted" to "坐姿",
        "skater" to "滑冰式",
        "ski" to "滑雪",
        "skier" to "滑雪者",
        "skin" to "翻转",
        "skull" to "头后",
        "slam" to "砸球",
        "sled" to "雪橇",
        "sledge" to "大锤",
        "slide" to "滑动",
        "slingers" to "悬摆",
        "smith" to "史密斯机",
        "snatch" to "抓举",
        "speed" to "速度",
        "spider" to "蜘蛛",
        "sphinx" to "狮身式",
        "spine" to "脊柱",
        "split" to "分腿",
        "sprint" to "冲刺",
        "sprints" to "冲刺",
        "squat" to "深蹲",
        "squats" to "深蹲",
        "squatting" to "蹲姿",
        "squeeze" to "夹胸",
        "stability" to "稳定",
        "stabilization" to "稳定",
        "staircase" to "楼梯",
        "stance" to "站距",
        "standing" to "站姿",
        "star" to "星式",
        "stationary" to "原地",
        "step" to "踏步",
        "stepbox" to "踏板",
        "stepmill" to "登阶机",
        "sternum" to "胸骨",
        "stiff" to "直腿",
        "stork" to "单脚站立",
        "straddle" to "跨坐",
        "straight" to "直",
        "strap" to "绑带",
        "straps" to "绑带",
        "stretch" to "拉伸",
        "stride" to "跨步",
        "style" to "式",
        "sumo" to "相扑",
        "superman" to "超人",
        "supinated" to "旋后",
        "supination" to "旋后",
        "supine" to "仰卧",
        "support" to "支撑",
        "supported" to "支撑",
        "suspended" to "悬吊",
        "system" to "系统",
        "svend" to "斯文德",
        "swimmer" to "游泳式",
        "swing" to "摆动",
        "sz" to "曲杆",
        "t" to "丁字",
        "tap" to "点地",
        "tate" to "泰特",
        "tennis" to "网球",
        "three" to "三",
        "through" to "穿越",
        "throw" to "抛",
        "thruster" to "推举深蹲",
        "thrusts" to "推髋",
        "tibialis" to "胫骨前肌",
        "tilt" to "倾斜",
        "tire" to "轮胎",
        "toe" to "脚尖",
        "touch" to "触碰",
        "touchers" to "触碰",
        "towel" to "毛巾",
        "trainer" to "训练器",
        "trap" to "斜方肌",
        "traps" to "斜方肌",
        "treadmill" to "跑步机",
        "tricep" to "肱三头",
        "triceps" to "肱三头",
        "tuck" to "收膝",
        "twin" to "双",
        "twist" to "转体",
        "twisted" to "扭转",
        "twisting" to "扭转",
        "twists" to "转体",
        "two" to "双",
        "under" to "下",
        "underhand" to "反握",
        "unilateral" to "单侧",
        "up" to "上",
        "upper" to "上",
        "upright" to "直立",
        "ups" to "起",
        "upward" to "向上",
        "v" to "窄握",
        "variation" to "变式",
        "vertical" to "垂直",
        "w" to "宽",
        "waiter" to "侍者",
        "walk" to "行走",
        "walking" to "行走",
        "wall" to "靠墙",
        "waist" to "腰腹",
        "weight" to "重量",
        "weighted" to "负重",
        "wheel" to "轮",
        "wide" to "宽握",
        "wind" to "风车",
        "windmill" to "风车",
        "wipers" to "雨刷",
        "world" to "世界",
        "wrist" to "手腕",
        "y" to "分叉",
        "yoga" to "瑜伽",
        "zercher" to "泽奇",
        "zottman" to "佐特曼",
    )

    private val ignoredWords = setOf(
        "a", "an", "and", "as", "at", "can", "for", "from", "in", "into",
        "of", "on", "out", "the", "to", "with", "without", "above", "across",
        "against", "between", "through",
    )

    fun translate(rawName: String): String =
        translationCache.getOrPut(rawName) { translateUncached(rawName) }

    private fun translateUncached(rawName: String): String {
        val trimmed = rawName.trim()
        if (trimmed.isBlank()) return "训练动作"
        if (cjkRegex.containsMatchIn(trimmed)) return trimmed

        val exactKey = trimmed.lowercase(Locale.ROOT)
        exactNameMap[exactKey]?.let { return it }

        var normalized = exactKey
            .replace("3/4", "四分之三")
            .replace("в°", "°")
            .replace("В°", "°")
            .replace("45°", "45度")
            .replace("°", "度")
            .replace("&", " and ")
            .replace("+", " plus ")
            .replace(punctuationRegex, " ")
            .replace(separatorRegex, " ")
            .replace(spaceRegex, " ")
            .trim()

        phraseRules.forEach { (rule, chinese) ->
            normalized = rule
                .replace(normalized, " $chinese ")
                .replace(spaceRegex, " ")
                .trim()
        }

        val parts = normalized
            .split(tokenSplitRegex)
            .mapNotNull(::translateToken)

        val result = cleanup(parts.joinToString(""))
        return result.ifBlank { "训练动作" }
    }

    private fun translateToken(token: String): String? {
        if (token.isBlank()) return null
        if (cjkRegex.containsMatchIn(token)) return token
        if (ignoredWords.contains(token)) return null
        if (token.matches(numberRegex)) return token
        return wordMap[token] ?: token.replace(latinRegex, "").ifBlank { null }
    }

    private fun cleanup(value: String): String =
        value
            .replace("器械器械", "器械")
            .replace("史密斯机器械", "史密斯机")
            .replace("史密斯机机", "史密斯机")
            .replace("自重自重", "自重")
            .replace("坐姿坐", "坐姿")
            .replace("站姿站", "站姿")
            .replace("弯举弯举", "弯举")
            .replace("推推", "推")
            .replace("拉拉", "拉")
            .replace("深蹲深蹲", "深蹲")
            .replace("提踵提举", "提踵")
            .replace("臂屈伸伸展", "臂屈伸")
            .replace("卧推推", "卧推")
            .replace("俯卧撑上", "俯卧撑")
}
